CMakeLists.txt
test/AllTestsMain.cpp

This PR adds a CMakeLists.txt to the project:
- The list file and possibly installed config files provide a library `oatpp::oatpp`.
- If `BUILD_SHARED_LIBS` is set, a shared library will be built. Otherwise (the default) a static library will be built.
- If `OATPP_INSTALL` is set (the default), an install target is generated that will install the library, its headers and cmake config files to the `CMAKE_INSTALL_PREFIX`.
- If `OATPP_BUILD_TESTS` is set (the default), the tests are built into a single executable and a test target is generated that will run these tests using CTest. To allow this, `test/AllTestsMain.cpp` was added that will provide a `main()` for running all tests if the macro `OATPP_ENABLE_ALL_TESTS_MAIN` is defined during compilation.
- To maintain CMakeLists.txt, new …

CMake support

---

core/macro/basic.hpp

Workaround until portable comma omission mechanism for empty __VA_ARGS__ is available
#13

portable 'OATPP_MACRO_HAS_ARGS'

---

CMakeLists.txt
src/oatpp-test/web/ClientServerTestRunner.hpp
src/oatpp/codegen/codegen_define_ApiController_.hpp
src/oatpp/core/async/Coroutine.cpp
src/oatpp/core/async/Coroutine.hpp
src/oatpp/core/async/Executor.cpp
src/oatpp/core/async/Processor.cpp
src/oatpp/core/async/worker/IOEventWorker_kqueue.cpp
src/oatpp/core/base/Countable.cpp
src/oatpp/core/base/memory/Allocator.hpp
src/oatpp/core/base/memory/ObjectPool.hpp
src/oatpp/core/concurrency/Thread.cpp
src/oatpp/core/data/mapping/type/Type.hpp
src/oatpp/core/data/stream/Stream.cpp
src/oatpp/core/utils/ConversionUtils.cpp
src/oatpp/core/utils/ConversionUtils.hpp
src/oatpp/web/mime/multipart/FileStreamProvider.cpp
src/oatpp/web/mime/multipart/StatefulParser.cpp
src/oatpp/web/protocol/http/Http.cpp
src/oatpp/web/protocol/http/outgoing/ChunkedBufferBody.cpp
src/oatpp/web/protocol/http/outgoing/MultipartBody.cpp
src/oatpp/web/server/AsyncHttpConnectionHandler.cpp
src/oatpp/web/server/HttpConnectionHandler.cpp
src/oatpp/web/server/HttpRequestHandler.hpp
test/oatpp/core/base/memory/MemoryPoolTest.cpp
test/oatpp/core/base/memory/PerfTest.cpp
test/oatpp/web/app/Controller.hpp
test/oatpp/web/app/ControllerAsync.hpp

Our code policy requires us to not use `sprintf` (only `snprintf` allowed) as well to write warningless code with `-Wextra` (and listen to clang-tidy as much as possible). I thought this may be relevant for code-quality/hardening of oatpp-upstream as well.

Warningless in -Wextra, hardened sprintf-calls.

---

src/CMakeLists.txt

In some environments, libatomic is not part of threads/stdlib/whatsoever. So for these environments, the libatomic needs specific linking. This is (for example) the case in some armvX and mips environments or openwrt.

Link against libatomic

---

src/oatpp/core/async/worker/IOEventWorker_epoll.cpp

Problem: Crash seen when loading build with oatpp.
Root Cause: When loading the build in gdb process gets EINTR and eventsCount is -1, hence crashing.
Fix: Its good to check EINTR before throwing error, hence added the same..
rgds
Balaji Kamal Kannadassan

 Fix. Fixed crash happening when debuggng via GDB.

---

src/oatpp/network/Url.cpp
src/oatpp/web/client/ApiClient.cpp
src/oatpp/web/protocol/http/incoming/RequestHeadersReader.cpp
src/oatpp/web/protocol/http/incoming/RequestHeadersReader.hpp
src/oatpp/web/server/HttpProcessor.cpp

Don't use std::move when it prevents copy elision (RVO?)
Reorder some initialization statements. 
and remove an unused variable.

Clean some warnings in Clang 10/Xcode 10.3

---

src/oatpp/encoding/Hex.cpp
src/oatpp/encoding/Unicode.cpp

Hex.cpp and Unicode.cpp were including winsock.h instead of winsock2.h which caused undefined functions for Universal Windows Platform builds.

Builds on UWP

---

src/oatpp/core/data/mapping/ObjectMapper.cpp
src/oatpp/parser/json/Beautifier.cpp
src/oatpp/web/protocol/http/incoming/BodyDecoder.cpp
src/oatpp/web/protocol/http/incoming/BodyDecoder.hpp

Use of `stream::BufferOutputStream` for uploads is inefficient due to excessive memory copy operations during buffer growth, taking too long to upload large files.
Using `stream::ChunkedBuffer` for uploads fixes this problem due to the no-copy buffer growth strategy.
Links:
- https://github.com/oatpp/oatpp/issues/198

Use stream::ChunkedBuffer instead of stream::BufferOutputStream for uploads

---

src/oatpp/web/server/HttpRouter.cpp
src/oatpp/web/url/mapping/Router.hpp

`Router::logRouterMappings` never shows the http-method a URL is mapped for. So when you have multiple methods for one URL, the method will display the URL multiple times. This could confuse users why their URL is shown multiple times ("Have I added the URL twice?", "Do I call `logRouterMappings` multiple times?", etc). Its also not easily visible if all methods are mapped as designed.
This small PR adds the http-method to the output of `logRouterMappings`.

Show http-method in logRouterMappings

---

src/oatpp/web/server/api/Endpoint.hpp
test/oatpp/web/server/api/ApiControllerTest.cpp

This PR adds the option to provide an custom response-description in `addResponse` (needed for swagger, see issue #212)

Response Description (Issue #212)

---

src/oatpp/core/data/mapping/type/Primitive.hpp
src/oatpp/core/data/mapping/type/Type.hpp
src/oatpp/core/utils/ConversionUtils.cpp
src/oatpp/core/utils/ConversionUtils.hpp
src/oatpp/parser/json/mapping/Deserializer.cpp
src/oatpp/web/client/ApiClient.cpp

Users were confused by `oatpp::String::empty()` method which was returning just empty string instead of checking string for being empty.
---
The new `oatpp::String::empty()` method, which does the check of the string being empty 
**should NOT be introduced** in a couple of next releases - in order to NOT introduce unexpected behavior in the user's code.

Refactor. Remove confusing 'empty()' method of ObjectWrappers.

---

src/CMakeLists.txt

It does not work successfully when  compiling oatpp using mingw. And oatpp should link system libraries wsock32 and ws2_32 on windows. So, I added it for support mingw compiler.

link win32 system libraries for mingw

---

src/oatpp/core/data/mapping/type/PairList.hpp
src/oatpp/core/data/mapping/type/Primitive.hpp
src/oatpp/core/data/mapping/type/UnorderedMap.hpp
src/oatpp/core/data/stream/Stream.cpp
src/oatpp/parser/json/mapping/Deserializer.cpp
src/oatpp/parser/json/mapping/Deserializer.hpp
src/oatpp/parser/json/mapping/Serializer.hpp
src/oatpp/web/client/ApiClient.hpp
test/CMakeLists.txt
test/oatpp/AllTestsMain.cpp
test/oatpp/core/data/mapping/type/ListTest.cpp
test/oatpp/core/data/mapping/type/ListTest.hpp
test/oatpp/core/data/mapping/type/PairListTest.cpp
test/oatpp/core/data/mapping/type/PairListTest.hpp
test/oatpp/core/data/mapping/type/PrimitiveTest.cpp
test/oatpp/core/data/mapping/type/PrimitiveTest.hpp
test/oatpp/core/data/mapping/type/StringTest.cpp
test/oatpp/core/data/mapping/type/StringTest.hpp
test/oatpp/core/data/mapping/type/UnorderedMapTest.cpp
test/oatpp/core/data/mapping/type/UnorderedMapTest.hpp
test/oatpp/core/data/mapping/type/VectorTest.cpp
test/oatpp/core/data/mapping/type/VectorTest.hpp
test/oatpp/parser/json/mapping/DTOMapperTest.cpp
test/oatpp/parser/json/mapping/DeserializerTest.cpp
test/oatpp/web/FullTest.cpp
test/oatpp/web/app/Controller.hpp

No more `<primitive>->getValue()`.
```cpp
oatpp::Int32 objV = 32;
v_int32 v = *objV;
bool eq = v == objV;
```

types. Simplify Primitives.

---

.gitignore
CMakeLists.txt
src/oatpp/core/base/Environment.cpp

Hello,
I created this PR because I'm having an issue about GCC version less than 5. The problem is due to std::put_time (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54354#c9). I added also in the .gitignore some generated folders and file of Visual Studio.

add check for gcc version less than 5 due to missing std::put_time

---

src/oatpp/core/IODefinitions.cpp
src/oatpp/core/IODefinitions.hpp

The `#include <WinSock2.h>` introduces `min` and `max` macros that clush with c++ `numeric_limits::min/max`.
To fix that I'm moving `WinSock2.h` include back to .cpp file. 
And the `INVALID_IO_HANDLE ` constant is now just manually defined as -1 which is rounded to max int32/int64.

IODefinitions. Move #include <WinSock2.h> back to .cpp file.

---

src/oatpp/network/virtual_/Interface.hpp

Since we've moved windows include from `UIDefinitions.hpp` there is no need to undefine the `interface` .

virtual_::Interface.hpp. No need to #undef interface.

---

src/oatpp/core/base/Environment.cpp
src/oatpp/core/base/Environment.hpp
test/CMakeLists.txt
test/oatpp/AllTestsMain.cpp
test/oatpp/core/base/LoggerTest.cpp
test/oatpp/core/base/LoggerTest.hpp

We received several wishes to implement a runtime configuration of enabled log-level (the latest one being #261).
In this PR, the individual loglevels are converted to a bitmask rather than an ongoing number. Thus we can enable and disable single log levels without side-affects for the other levels.
However, to keep the `Logger` interface as generic as possible, this is only implemented for the `DefaultLogger`, not the interface. The new function `oatpp::base::Environment::getLogger()` is generic as well and only returns `std::shared_ptr<Logger>`. Therefore, the user has to use a pointer cast to `std::shared_ptr<DefaultLogger>` to be able to call the `disablePriority()` and `enablePriority()` functions. This is a design limitation to keep everything generic and extensible. 
```c++
auto …
```

Proposal for #261: Fine grained configurable Loglevel

---

src/CMakeLists.txt
src/oatpp/core/data/stream/BufferStream.cpp
src/oatpp/core/data/stream/BufferStream.hpp
src/oatpp/core/utils/Binary.cpp
src/oatpp/core/utils/Binary.hpp
src/oatpp/web/protocol/http/encoding/Chunked.cpp
src/oatpp/web/protocol/http/outgoing/Request.cpp
src/oatpp/web/server/HttpProcessor.cpp
src/oatpp/web/server/HttpProcessor.hpp
test/oatpp/AllTestsMain.cpp
test/oatpp/core/data/stream/BufferStreamTest.cpp

Make the `oatpp::data::stream::BufferOutputStream` to grow by a factor of 2.
The [m_maxCapacity](https://github.com/oatpp/oatpp/compare/optimize_buffer_output_stream?expand=1#diff-f48230c096b596650980d36d03f1a28dR40) parameter will be configurable later - in order to avoid silent bugs.

oatpp::data::stream::BufferOutputStream. Optimize growth.

---

src/oatpp/core/data/mapping/type/Type.hpp
test/oatpp/core/data/mapping/type/ObjectTest.cpp

Just the first step to have something like the following working:
```cpp
DTO_FIELD_INFO(start_date) {
info->description = "Your start date";
info->pattern = "^\d{4}-\d{2}-\d{2}$";
}
DTO_FIELD(String, start_date);
```
So in `oatpp-swagger` we can just pass it through and make the OAS like:
```json
"start-date": {
"type": "string",
"pattern": "^\d{4}-\d{2}-\d{2}$" // <- some swagger clients may now validate the string date with this
},
```

Adds pattern to the info, to be used in swagger

---

src/oatpp/network/server/Server.cpp
src/oatpp/network/server/Server.hpp

This hides the needed threading to make the server non-blocking for
inexperienced users or those who do not want to run their own threading
concept.

Draft for an optional non-blocking call to `Server::run`

---

src/oatpp/codegen/api_controller/base_define.hpp

This is just a small workaround for issue #203. Doing a small check here does not introduce any "online"-costs since its just excecuted at startup.
It prevents us from unnecessary checks in the functions that are run every time a new request comes in.

Fix for long lasting issue #203 (Closes #203)

---

src/oatpp/core/base/StrBuffer.hpp
src/oatpp/core/base/memory/Allocator.hpp
src/oatpp/core/base/memory/ObjectPool.hpp
src/oatpp/core/data/buffer/IOBuffer.hpp
src/oatpp/core/data/stream/ChunkedBuffer.hpp

https://github.com/oatpp/oatpp/issues/308

Issue #308: oatpp::base::memory::MemoryPool::freeByEntryHeader()]: Invalid EntryHeader

---

src/oatpp/core/base/Environment.cpp
src/oatpp/core/base/Environment.hpp
test/oatpp/core/base/LoggerTest.cpp
test/oatpp/core/base/LoggerTest.hpp

With log-categories users of Oat++-logging can take advantage of a fine grained logging mechanism.
Each log-category has its own set of enabled priorities, its own tag and can be disabled/enabled altogether.
Instead of just offering some priority-levels the user can now create as much logging categories as s:he wants and tune visibility of priorities by each category.
The API can be used optionally on top of the default logging mechanisms without breaking or changing any functionality of the old system. One can even mix both "legacy-style" and "category-style" logging in the same function/class/program.

Introducing log-categories

---

src/oatpp/codegen/api_controller/base_define.hpp
src/oatpp/web/server/api/Endpoint.hpp

- Add example field to EndpointInfo::Param
- Better API for `EndpointInfo::addConsumes`, `EndpointInfo::addResponse`
- Set Endpoint `info->bodyContentType` according to controller's default object mapper.
- Return error if endpoint consumes `BODY_DTO` but no default object mapper was set for controller
- Set Endpoint `info->body.required = true;` if `BODY` or `BODY_DTO` parameter is present in `ENDPOINT`.
Links:
- https://github.com/oatpp/oatpp-swagger/issues/33
- https://github.com/oatpp/oatpp/issues/368

EndpointInfo: Add example field for parameters.

---

src/oatpp-test/UnitTest.hpp
src/oatpp-test/web/ClientServerTestRunner.hpp
src/oatpp/network/Server.cpp
src/oatpp/network/Server.hpp
test/oatpp/web/PipelineTest.cpp

Instead of an external invocation of `stop()` to stop a running server, one could pass an lambda that returns true when the server should continue to run or false if it should stop.
Ideally this function should return as fast as possible and only do minimal amount of work. Like an interrupt function in µC.
This would ease the implementation of simple stopping mechanism that do not require external threads or other management.
For more complex functions, the minimal `bool()` function can be bound with `std::bind` to pass parameters etc.
In src/oatpp-test/web/ClientServerTestRunner.hpp a quick and dirty example is shown how a lambda is passed to `run()` which does nothing but return an bool that is modified somewhere other. This part isn't meant to be merged just as a dirty example. …

WIP/Discussion: Let server check an (optional) stopping condition by itself

---

src/oatpp/network/Server.cpp

If `server->run()` is called (no argument given, thus `conditional` is `nullptr`) the `conditionalMainLoop` was called instead of the normal `mainLoop`.
First reported in Issue #372.
Now the correct normal `mainLoop` is called when no conditional function was given.

Fix wrong calling of conditional loop if condition is null (Closes #372)

---

src/oatpp/codegen/api_controller/base_define.hpp
test/oatpp/web/FullTest.cpp
test/oatpp/web/app/Client.hpp
test/oatpp/web/app/Controller.hpp

This PR adds a fourth parameter to QUERY() where the string-representation of an default-value can be set. Thus allowing for optional QUERY parameters.

Add optional default-value for QUERY parameters to ease the implementation of optional QUERY parameters

---

src/oatpp/web/server/AsyncHttpConnectionHandler.cpp
src/oatpp/web/server/AsyncHttpConnectionHandler.hpp
src/oatpp/web/server/HttpConnectionHandler.cpp
src/oatpp/web/server/HttpConnectionHandler.hpp
src/oatpp/web/server/HttpProcessor.cpp
src/oatpp/web/server/HttpProcessor.hpp

To reliable stop a ConnectionHandler it needs to count its spawned threads and wait for all threads to be done before stopping.
Because we can have multiple ConnectionHandlers, this counting can not be done via the `Components` since they *could* be shared between multiple ConnectionHandlers.
Thus we have to pass the counter separately.
While the counting can easily be done in the constructor and destructor of the Async-Api's `Coroutine` since it's threadpool cleanly allocs and deallocs the `Coroutine` the Simple-Api needs to be counted in the `Task::run()` method. It seems that `std::thread` does not deallocates the passed `HttpProcessor::Task` as expected (e.g. when the thread is done).

Let the ConnectionHandlers count how many threads they spawn.

---

src/oatpp/network/Server.cpp
src/oatpp/network/Server.hpp

This PR adds some advice and hints to the threading-examples how to implement own threading when the deprecated threaded `run(true)` is removed.

Add hints and advice to the threading-examples in `Server.hpp`

---

src/oatpp/network/tcp/server/ConnectionProvider.cpp

Typicaly in case we use a port equal 0 to let the system find a free port, we need to update the port property of the provider

Update port after binding

---

src/oatpp/core/async/Executor.cpp

Hi,
while browsing your source code I found these two functions which create a new std::runtime_error on the stack, but never throw it.
I think the throw keyword was forgotten.
PS: This is my first ever contribution to open source projects. If I overlooked something in the workflow, please let me know.

Added missing throw keyword

---

src/oatpp/core/async/Coroutine.cpp
src/oatpp/core/async/Coroutine.hpp

Since the destructors call the delete operator, it should also be called in the move assignement operators.

Fixed memory leak in move assignement operators

---

src/oatpp/core/data/mapping/type/Enum.hpp
test/oatpp/core/data/mapping/TypeResolverTest.cpp
test/oatpp/core/data/mapping/type/AnyTest.cpp
test/oatpp/core/data/mapping/type/PrimitiveTest.cpp

When comiling the project with MSVC I got a few warnings for truncations and unreferenced variables.
Clang/GCC also produce the truncation warnings if the -Wconversion flag is set.

Fixed compiler warnings

---

src/oatpp/parser/json/Utils.cpp
src/oatpp/parser/json/Utils.hpp
src/oatpp/parser/json/mapping/Serializer.cpp
src/oatpp/parser/json/mapping/Serializer.hpp

Now user can disable `'/'` escaping. 
String `"https://oatpp.io/"` will be serialized as `"https://oatpp.io/` instead of `"https:\/\/oatpp.io\/"`
```cpp
objectMapper->getSerializer()->getConfig()->escapeFlags &= !oatpp::parser::json::Utils::FLAG_ESCAPE_SOLIDUS;
```
Links:
- #381

json::mapping::Serializer::Config: Introduce escapeFlags (#381)

---

src/oatpp/core/async/worker/IOEventWorker_epoll.cpp

I've branched from 1.2.5 and implemented a fix for Android API 19, as it does not support the epoll_create1 interface and should instead use the older epoll_create.
See https://github.com/android/ndk/issues/394 for more information.

Android API 19 does not support the epoll_create1

---

src/oatpp/web/client/HttpRequestExecutor.cpp

ClientConnectionPool: close pool-connection if server has closed it

---

src/oatpp/web/protocol/http/outgoing/Response.cpp
src/oatpp/web/protocol/http/outgoing/Response.hpp

Added getter for `m_body` of responses. Useful for response interceptors or similar.

Added getter for `m_body` of `Response`

---

changelog/1.3.0.md
src/CMakeLists.txt
src/oatpp/core/data/stream/BufferStream.cpp
src/oatpp/core/data/stream/BufferStream.hpp
src/oatpp/core/data/stream/FIFOStream.cpp
src/oatpp/core/data/stream/FIFOStream.hpp
src/oatpp/core/data/stream/Stream.hpp
src/oatpp/core/data/stream/StreamBufferedProxy.cpp
src/oatpp/core/data/stream/StreamBufferedProxy.hpp

Oat++ Streams are great! However, I always missed a buffered stream that acts as `InputStream` with a writable buffer. `InputBufferStream` only works with an static memory.
To solve this `FIFOStream` is an `InputStream` that also has an write-callback to dynamically insert more data to the buffer.
As a bonus, it is resizeable.
Now we have several buffered streams that somehow expose similar APIs that kind of do the same. `BufferedInputStream` is a new interface that unifies those different APIs and enables generalization.

Streams: New `FIFOStream` stream and `BufferedInputStream` interface

---

src/oatpp/core/data/buffer/FIFOBuffer.cpp
src/oatpp/core/data/buffer/FIFOBuffer.hpp

`FIFOBuffer` should accept an `WriteCallback`/`ReadCallback` to its `readAndWriteToStream` and `readFromStreamAndWrite` functions.
There is no need to specialize on a `Stream`.
Its an non-breaking change. Also renaming the functions to `readAndWriteToCallback` and `readFromCallbackAndWrite` would break things.

`FIFOBuffer` should accept an `WriteCallback`/`ReadCallback`

---

changelog/1.3.0.md
src/oatpp/core/data/mapping/type/Primitive.hpp

As suggested in #470, the typecast operator from `oatpp::String` to `std::string` is included. 
Furthermore, to get `oatpp-swagger` running again, a case insensitive string comparison is required. For this purpose the `oatpp::String` class gets the following new methods:
```cpp
inline bool equalsCI(const std::string &sb) ;
inline bool equalsCI(const String &b);
inline bool equalsCI(const char *b);
```
Finally, trialling whitespaces are removed.
Closes: #470

oatpp::String works better with std::string

---

src/oatpp/orm/Executor.cpp

Hi,
It seems that GCC doesn't support well initializer for ParamsTypeMap ([see this build](https://github.com/Yadoms/yadoms/runs/3535646691?check_suite_focus=true)), error was something like :
`
/work/projects/external-libs/oatpp/src/oatpp_build/src/oatpp/orm/Executor.cpp:42:64: error: converting to 'const ParamsTypeMap {...}' from initializer list would use explicit constructor '...'
`
This PR suggest a simple workaround using default ctor of ParamsTypeMap instead of empty initializer at parseQueryTemplate call.

Try to fix cross compilation for Raspberry/Synology

---

src/oatpp/web/server/handler/ErrorHandler.hpp

Virtual destructor added to the ErrorHandler since derived class
destructor should be called when destroying an object via a pointer to
the base type (ErrorHandler in this case).
More info: https://stackoverflow.com/a/461224/6067014

Add ErrorHandler virtual destructor

---

changelog/1.3.0.md
src/oatpp/core/provider/Provider.hpp

- Client code:
```
m_socket->getConnection().invalidator->invalidate(m_socket->getConnection().object);
```
is simplified to:
```
m_socket->getConnection().invalidate();
```
- Updated migration doc;
- Fixed typos.

Add a convenience invalidate() method to ResourceHandleTemplate. 

---

src/oatpp/core/base/Environment.cpp

This patch restores correct colorized output for `OATPP_LOGx()`
Tested on Linux only

fix: wrong ANSI color codes in DefaultLogger::log()

---

src/oatpp/parser/json/Utils.cpp
src/oatpp/parser/json/Utils.hpp
src/oatpp/parser/json/mapping/Deserializer.cpp
test/oatpp/parser/json/mapping/DeserializerTest.cpp

Currently the parsing of `oatpp::Any` can only parse numbers to `oatpp::Float64`.
In my use case I need exact parsing for integer types. Therefore we need to guess the integer type of a JSON "integer" value.
This PR extends the `Deserializer::guessNumberType` function to search for a decimal separator. If no is found in the next word we have an integer value. Depending on the first character it is then parsed as `UInt64` or `Int64`.
I also added tests that checks all supported cases for `oatpp::Any` parsing.

allow oatpp::Any to parse directly to UInt64 or Int64

---

src/oatpp/parser/json/Utils.cpp
test/oatpp/parser/json/mapping/DeserializerTest.cpp

I noticed that my last PR (https://github.com/oatpp/oatpp/pull/529) introduced a bug when parsing a negative number in oatpp::Any. This commit fixes this and adds more tests to ensure all cases are correctly handled.

fix negativ number parsing in oatpp::Any

---

src/oatpp/codegen/api_controller/base_define.hpp
src/oatpp/core/async/Error.cpp
src/oatpp/core/async/Error.hpp
src/oatpp/web/protocol/http/Http.cpp
src/oatpp/web/protocol/http/Http.hpp
src/oatpp/web/server/HttpProcessor.cpp
src/oatpp/web/server/api/ApiController.cpp
src/oatpp/web/server/api/ApiController.hpp
src/oatpp/web/server/handler/ErrorHandler.cpp
src/oatpp/web/server/handler/ErrorHandler.hpp
test/CMakeLists.txt
test/oatpp/web/FullTest.cpp
test/oatpp/web/app/Client.hpp
test/oatpp/web/app/ControllerWithErrorHandler.hpp

Adds support to ErrorHandler to handle the original thrown exception.
Adds support to ApiController to assign a custom error handler at the controller level.
If the ApiController does not define an error handler, the ConnectionHandler registered error handler will handle the exception.
The changes are backwards compatible. Any currently implemented ErrorHandlers will still work since the new virtual method has a default implementation that will pass the exception info to the now deprecated methods.
The following ErrorHandler methods have been deprecated and should be removed in the next breaking release.
```c++
virtual 
std::shared_ptr<protocol::http::outgoing::Response> 
handleError(const protocol::http::Status& status, const oatpp::String& message, const Headers& headers) = 0; …
```

Add new virtual handleError method to handle the original error

---

src/oatpp/core/IODefinitions.cpp
src/oatpp/core/base/Environment.cpp
src/oatpp/encoding/Hex.cpp
src/oatpp/encoding/Unicode.cpp
src/oatpp/network/tcp/Connection.cpp
src/oatpp/network/tcp/client/ConnectionProvider.cpp
src/oatpp/network/tcp/server/ConnectionProvider.cpp

When cross-compiling using clang on Linux to target Windows, the build fails due to the mixed case spelling of the header includes. Clang expects the headers to be all lowercase.

Cross-compile Windows Fix

---

src/oatpp/parser/json/Utils.cpp
src/oatpp/parser/json/Utils.hpp

non-ASCII(utf8) characters can output as it's origin bytes other than an unicode encoding form.
#662

Support for disabling escaping of non-ASCII when serializing DTOs

---

src/oatpp/core/data/mapping/type/Type.cpp
src/oatpp/core/data/share/StringTemplate.cpp
src/oatpp/core/data/stream/FileStream.cpp
src/oatpp/network/monitor/ConnectionMonitor.cpp
src/oatpp/network/tcp/server/ConnectionProvider.cpp
src/oatpp/parser/json/Utils.cpp
src/oatpp/web/server/handler/ErrorHandler.cpp
test/oatpp/core/data/mapping/type/ObjectTest.cpp
test/oatpp/core/data/mapping/type/ObjectWrapperTest.cpp
test/oatpp/core/data/mapping/type/StringTest.cpp

Notes on build-warning-changes branch pull request.
_Pragma keyword
https://learn.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword
src/oatpp/core/data/stream/FileStream.cpp
disable 'fopen vs fopen_s' warning
https://en.cppreference.com/w/c/io/fopen
#if defined(WIN32) || defined(_WIN32)
_Pragma("warning(disable : 4996)")
#endif
test/oatpp/core/data/mapping/type/ObjectWrapperTest.cpp
test/oatpp/core/data/mapping/type/StringTest.cpp
disable warning:
warning C4101: 'e': unreferenced local variable
#if defined(WIN32) || defined(_WIN32)
_Pragma("warning(disable : 4101)")
#endif
src/oatpp/web/server/handler/ErrorHandler.cpp
disable warnings: 
warning C4068: unknown pragma 'GCC'
warning C4996: 'oatpp::web::server::handler::ErrorHandler::handleError': was declared …

kushnertodd fix to issue #724 Remove warnings from Windows build

---

cmake/project.cmake

Don't insert paths into regular expressions,
paths can contain regular expression meta characters which will get evaluated.
Process file lists manually and use cmake_path(IS_PREFIX) to filter paths.
Closes #761

Fix CMake regular expression injection

---

src/oatpp/network/Server.cpp

Hello,
We use Oatpp on a 32-bit ARM platform, and recently noticed that the web server would occasionally fail to start. After investigating, the cause was found to be the use of `compare_exchange_weak` during the server start up. As I understand it, `Server::setStatus` will set the new status, provided the existing value of status is equal to the expected value. During start up, the status will transition from `CREATED` to `STARTING` to `RUNNING`, and the web server will continue to run while the status is `RUNNING`.
The issue is that the comparison between the existing and expected state is done via `compare_exchange_weak`, and according to the [documentation](https://en.cppreference.com/w/cpp/atomic/atomic/compare_exchange):
> The weak forms (1-2) of the functions are allowed to fail …

Fix web server spuriously failing to start on 32-bit ARM

---

cmake/compiler-flags.cmake

Enable compiler warnings (-Warith-conversion)

---

src/oatpp/core/data/mapping/type/Type.cpp
src/oatpp/core/data/share/MemoryLabel.hpp

The compiler didn't catch this one in the oatpp build, but did catch it in the project in which we integrated oatpp.
See #784

Fix compiler warnings (-Wuseless-cast)

---

src/CMakeLists.txt
src/oatpp/network/tcp/ConnectionConfigurer.hpp
src/oatpp/network/tcp/server/ConnectionProvider.cpp
src/oatpp/network/tcp/server/ConnectionProvider.hpp

fix #775
User can implement `ConnectionConfigurer`, and add it to `ConnectionProvider` by `setConnectionConfigurer` method to achieve the setting of the Socket options

Add Interface ConnectionConfigurer

---

.gitignore

This allows to use multiple build directories easily, the underscore pattern is for my very own selfish needs 😄. The removed patterns contain a typo and shouldn't be required for CMake builds anyway.

Ignore more build directory patterns

---

cmake/project.cmake

Without quotes list expansion happens inside the set-call, if the list is empty, this actually unsets the variable. This is not intended and could lead to unwanted side effects. List expansion is not required there, quoting the variable results in setting the variable to empty for empty lists.

Prevent unintended removal of local CMake variables

---

cmake/compiler-flags.cmake

New fix of [872](https://github.com/oatpp/oatpp/issues/872) based on discussion with @fhuberts .
This fix tries to enable `-fcf-protection` when conditions are met, instead of simply disabling it all the time.
Tried building on a typical x86_64 Debian 12 (on which `-fcf-protection` is supported) and a Raspberry Pi (Raspberry Pi OS 12, on which `-fcf-protection` is not supported) and both are successful. `make test` on both devices are also successful.

New fix to issue 872

---

src/oatpp-test/web/ClientServerTestRunner.hpp

Move OATPP_COMPONENT calls to constructor to allow supplying variables without using DI.
This is consistent with other constructors, which allow you to supply variables via the constructors instead of using the Oatpp environment DI.

Allow overriding DI injected variables in ClientServerTestRunner

---

cmake/compiler-flags.cmake

I was not able to cross-build for Raspberry Pi from Ubuntu with GCC 4.9 (symptoms were very similar to [this issue](https://github.com/oatpp/oatpp/issues/872)).
I found that `-fstack-clash-protection` flag was added to GCC in v8.1.
This PR intends to fix this. It works now on my GCC 4.9 based cross-build.

Try to fix cross-compile for Raspberry Pi with GCC version < 8.1

---

cmake/compiler-flags.cmake

The compiler flag `-fcf-protection` is only available since GCC 8.1.
Closes #892

Fix compilation on GCC 4.6

---

src/oatpp/core/base/Environment.hpp

Include `cstdarg` to fix the following build failure with uclibc-ng:
```
In file included from /home/autobuild/autobuild/instance-4/output-1/build/oatpp-1.3.0/src/oatpp/algorithm/CRC.hpp:28,
from /home/autobuild/autobuild/instance-4/output-1/build/oatpp-1.3.0/src/oatpp/algorithm/CRC.cpp:25:
/home/autobuild/autobuild/instance-4/output-1/build/oatpp-1.3.0/src/oatpp/core/base/Environment.hpp:359:93: error: 'va_list' has not been declared
359 |   static void vlogFormatted(v_uint32 priority, const std::string& tag, const char* message, va_list args);
|                                                                                             ^~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/bcdf7548ff752f936defd111d13c63245ea70cbe

src/oatpp/core/base/Environment.hpp: include cstdarg

---

fuzzers/oatpp/json/ObjectMapper.cpp

Improvements:
1. Add all available types for DTO
2. Randomize the deserializer config
3. Call `writeToString` on parsed DTO
Coverage was increased by ~20% and two bugs were found, I will report them separately

Improve coverage for ObjectMapper fuzzer

---

src/oatpp/async/Processor.hpp

Member var m_isrunning is accessed from msleepsettask before
the former is constructed, resulting in a race condition. Fix
is to construct and run the thread only after all members have
constructed.
Found by tsan.

Fix race on construction / access in processor thread

---

src/oatpp/codegen/dto/base_define.hpp
src/oatpp/data/type/Enum.hpp
src/oatpp/data/type/List.hpp
src/oatpp/data/type/Object.hpp
src/oatpp/data/type/PairList.hpp
src/oatpp/data/type/UnorderedSet.hpp
src/oatpp/data/type/Vector.hpp

This pull request addresses the issues #793 and #913
By the use of std::unique_ptr, memory leaks are avoided.

#793 #913 Use unique pointers to avoid memory leaks
