src/oatpp/core/async/Coroutine.cpp, src/oatpp/core/async/Coroutine.hpp, src/oatpp/core/async/Executor.cpp, src/oatpp/core/async/Executor.hpp, src/oatpp/core/async/worker/IOEventWorker.hpp, src/oatpp/core/async/worker/IOEventWorker_common.cpp, src/oatpp/core/async/worker/IOEventWorker_epoll.cpp, src/oatpp/core/async/worker/IOEventWorker_kqueue.cpp, src/oatpp/core/async/worker/IOWorker.cpp, src/oatpp/core/async/worker/IOWorker.hpp, src/oatpp/core/async/worker/TimerWorker.cpp, src/oatpp/core/async/worker/TimerWorker.hpp, src/oatpp/core/async/worker/Worker.hpp, src/oatpp/core/data/stream/Stream.hpp
Fix for https://github.com/oatpp/oatpp/issues/67
=> Full duplex mode support for io event worker

CONTRIBUTING.md
This looks like an exciting project! I'll definitely be keeping an eye on it. I wrote my MSc thesis on benchmarking WebSocket servers but sadly haven't touched `C++` much. Nonetheless, here are some typo fixes 😊
=> Fix README typos

src/oatpp/core/base/Environment.cpp, src/oatpp/core/data/buffer/FIFOBuffer.cpp, src/oatpp/core/data/stream/ChunkedBuffer.cpp, src/oatpp/network/Connection.cpp
So that it will build in Xcode
=> Use explicit casting when truncating long numbers

src/oatpp-test/web/ClientServerTestRunner.hpp, src/oatpp/core/async/Executor.hpp, src/oatpp/core/async/Processor.cpp, src/oatpp/core/async/worker/IOEventWorker.hpp, src/oatpp/core/async/worker/TimerWorker.hpp
=> fix thread sanitizer warnings

src/oatpp/network/server/SimpleTCPConnectionProvider.cpp
Gives the ability to use oat++ on an embedded system without IPv6.
=> Add INET support for linux (not just INET6)

src/CMakeLists.txt, src/oatpp/network/server/SimpleTCPConnectionProvider.cpp
I don't really use CMake much so my solution to the linking issue is bad, but in case others aren't aware of the issue here is my fix.
=> Minor changes for Building on FreeBSD 12.1

src/oatpp/core/base/memory/Allocator.hpp, src/oatpp/web/protocol/http/outgoing/Response.cpp
Hi,
I have removed some unnecessary semicolons and one unused variable.
=> Small cleanup

src/oatpp/core/base/Environment.cpp
Hi,
I have removed one useless cast to comply with `-Wuseless-cast` flag.
=> Remove useless cast

src/oatpp/core/async/worker/IOEventWorker_epoll.cpp, src/oatpp/core/data/stream/BufferStream.cpp, src/oatpp/core/data/stream/ChunkedBuffer.cpp, src/oatpp/core/data/stream/FileStream.cpp, src/oatpp/parser/json/Beautifier.cpp, src/oatpp/parser/json/mapping/Serializer.cpp, src/oatpp/parser/json/mapping/Serializer.hpp, src/oatpp/web/client/RetryPolicy.cpp, src/oatpp/web/protocol/http/outgoing/BufferBody.cpp
Hi,
I have commented out unused parameters to comply with `-Wunused-parameter` flag.
=> Comment unused parameters.

src/oatpp/core/base/StrBuffer.cpp, src/oatpp/core/data/buffer/Processor.cpp, src/oatpp/parser/json/mapping/Deserializer.cpp, src/oatpp/parser/json/mapping/Serializer.cpp
To comply with `-Wsign-compare` flag.
=> Fix comparison of signed and unsigned integers.

src/CMakeLists.txt, src/oatpp/core/Types.hpp, src/oatpp/core/data/mapping/ObjectMapper.hpp, src/oatpp/core/data/mapping/type/Object.hpp, src/oatpp/core/data/mapping/type/Type.hpp, src/oatpp/core/data/mapping/type/UnorderedSet.cpp, src/oatpp/core/data/mapping/type/UnorderedSet.hpp, src/oatpp/parser/json/mapping/Deserializer.cpp, src/oatpp/parser/json/mapping/ObjectMapper.hpp, src/oatpp/parser/json/mapping/Serializer.cpp, test/CMakeLists.txt, test/oatpp/AllTestsMain.cpp, test/oatpp/core/data/mapping/type/UnorderedSetTest.cpp, test/oatpp/core/data/mapping/type/UnorderedSetTest.hpp, test/oatpp/parser/json/mapping/UnorderedSetTest.cpp, test/oatpp/parser/json/mapping/UnorderedSetTest.hpp
Add `UnorderedSet` to mapping-enabled collections.
=> Collection unordered set

src/oatpp/core/base/Environment.cpp
Hello Leonid,
While reading some portions of the code of oatpp i found this typo in few exception messages.
This is my very humble contribution to this amazing project ;-)
Hope this can help somehow.
best regards,
Olivier.
=> Fixed few typos

src/oatpp/network/client/SimpleTCPConnectionProvider.cpp
=> Added error message to failed getaddrinfo throw

test/oatpp/core/data/share/StringTemplateTest.cpp
Fix issue described in [this post](https://stackoverflow.com/questions/64566489/oat-installation-failed-on-centos-7)
=> Tests. StringTemplateTest. Fix ambiguity in the method call.

changelog/1.2.5.md, src/oatpp/web/server/api/Endpoint.hpp
Links:
- https://github.com/oatpp/oatpp/issues/368
=> Endpoint: Support multiple example values.

src/oatpp/web/server/interceptor/RequestInterceptor.hpp
RequestInterceptor needs virtual destructor
=> RequestInterceptor needs virtual destructor

src/oatpp/core/async/Processor.cpp, src/oatpp/core/data/stream/BufferStream.cpp, src/oatpp/core/data/stream/Stream.cpp, src/oatpp/network/tcp/server/ConnectionProvider.cpp, src/oatpp/web/protocol/http/outgoing/Request.cpp
Hi,
I made some small refactorings.
In my opinion the added override specifiers are especially important.
=> Minor refactorings

src/oatpp/core/data/mapping/type/Object.hpp
Resolves https://github.com/oatpp/oatpp/issues/417
Relates to https://github.com/oatpp/oatpp-swagger/pull/48
=> add bool required to Property.Info

src/oatpp/web/protocol/http/outgoing/Body.hpp, src/oatpp/web/protocol/http/outgoing/BufferBody.cpp, src/oatpp/web/protocol/http/outgoing/BufferBody.hpp, src/oatpp/web/protocol/http/outgoing/MultipartBody.cpp, src/oatpp/web/protocol/http/outgoing/MultipartBody.hpp, src/oatpp/web/protocol/http/outgoing/Response.cpp, src/oatpp/web/protocol/http/outgoing/StreamingBody.cpp, src/oatpp/web/protocol/http/outgoing/StreamingBody.hpp
Hello,
Creating this PR to not forget about the changes.
There were 2 issues:
1) Having int64 in getKnownSize to properly work with big values in Content-Length.
2) Properly check for getKnownSize to show Content-Length (if available), instead of Transfer-Encoding.
You can, of course, close the PR and add changes on your own. 
I would prefer using non-forked repo. 
Thanks
=> Catching up with streaming changes

src/oatpp/core/data/mapping/type/Primitive.cpp, src/oatpp/core/data/mapping/type/Primitive.hpp, src/oatpp/core/data/share/MemoryLabel.hpp, src/oatpp/core/utils/String.cpp, src/oatpp/core/utils/String.hpp, src/oatpp/network/Url.cpp, src/oatpp/orm/SchemaMigration.cpp, src/oatpp/web/protocol/http/utils/CommunicationUtils.cpp, test/oatpp/core/data/buffer/ProcessorTest.cpp, test/oatpp/core/data/mapping/type/StringTest.cpp
Improvements to https://github.com/oatpp/oatpp/pull/471
=> oatpp::String: better convenience methods.

src/oatpp/network/Server.cpp, src/oatpp/network/Server.hpp
We may need synchronization for that.
=> Add setter for `Server`s `ConnectionProvider`.

src/oatpp/web/protocol/http/outgoing/ResponseFactory.cpp, src/oatpp/web/protocol/http/outgoing/ResponseFactory.hpp, src/oatpp/web/server/api/ApiController.cpp, src/oatpp/web/server/api/ApiController.hpp, src/oatpp/web/server/api/Endpoint.hpp, test/oatpp/web/server/api/ApiControllerTest.cpp
=> Add helpers for creating empty message-body responses

src/oatpp/web/client/HttpRequestExecutor.cpp, test/oatpp/web/FullAsyncTest.cpp, test/oatpp/web/FullTest.cpp, test/oatpp/web/app/Client.hpp, test/oatpp/web/app/Controller.hpp, test/oatpp/web/app/ControllerAsync.hpp
Closes #525 
I used a `BufferOutputStream` to concatenate strings, don't hesitate to tell me if there is a better way to do it!
=> fix: add port in host header

src/oatpp/web/mime/multipart/PartList.cpp, src/oatpp/web/mime/multipart/PartList.hpp, test/oatpp/web/mime/multipart/StatefulParserTest.cpp
=> Added support for multiple parts with same name in oatpp::web::mime::multipart::PartList

src/oatpp/codegen/ApiClient_define.hpp, src/oatpp/codegen/api_controller/base_define.hpp, src/oatpp/codegen/dto/base_define.hpp, src/oatpp/codegen/dto/enum_define.hpp
This PR fixes little _**"macoro"**_ typos in documentation. Changed them to **_"macro"_**. ✨
=> Fix some typos in documentation 📖

src/oatpp/orm/SchemaMigration.cpp, src/oatpp/orm/SchemaMigration.hpp
=> orm::SchemaMigration: add 'getSchemaVersion' method

CMakeLists.txt, src/CMakeLists.txt
New PR as a follow-up on https://github.com/oatpp/oatpp/pull/541
=> Introduce OATPP_LINK_TEST_LIBRARY

src/oatpp/core/data/mapping/type/PairList.hpp
See:
https://github.com/oatpp/oatpp/issues/554
=> Delete redundant assignments

src/oatpp/core/data/mapping/type/Any.cpp, src/oatpp/core/data/mapping/type/Any.hpp, src/oatpp/core/data/mapping/type/Primitive.cpp, src/oatpp/core/data/mapping/type/Primitive.hpp
see https://github.com/oatpp/oatpp/issues/557
=> move the getType() function implementation from hpp file to cpp file

src/oatpp/core/data/mapping/type/Object.hpp, src/oatpp/core/data/stream/Stream.cpp, src/oatpp/core/data/stream/Stream.hpp, src/oatpp/core/utils/ConversionUtils.cpp, src/oatpp/parser/json/mapping/Serializer.cpp, src/oatpp/parser/json/mapping/Serializer.hpp, test/CMakeLists.txt, test/oatpp/AllTestsMain.cpp, test/oatpp/parser/json/mapping/FloatTest.cpp, test/oatpp/parser/json/mapping/FloatTest.hpp
=> Supported for specifying float value format on serializing DTO to JSON

src/oatpp/core/data/mapping/ObjectMapper.hpp, test/CMakeLists.txt, test/oatpp/AllTestsMain.cpp, test/oatpp/parser/json/mapping/BooleanTest.cpp, test/oatpp/parser/json/mapping/BooleanTest.hpp
=> Fix parsing of Boolean

src/oatpp/network/tcp/client/ConnectionProvider.cpp
I found the error description helpful while debugging an issue.
=> Adds additional error context to exceptions on connect() calls

src/oatpp/core/base/Environment.cpp
This is just for correctness - I did not have any problems with destroy so far.
=> Fix possible race condition on destroy

src/oatpp-test/UnitTest.hpp, src/oatpp/core/async/ConditionVariable.hpp, src/oatpp/core/base/Environment.hpp, src/oatpp/core/data/share/MemoryLabel.hpp, test/oatpp/core/data/mapping/type/ObjectTest.cpp, test/oatpp/web/app/Controller.hpp
https://github.com/oatpp/oatpp/issues/784
=> Fix compiler warnings (-Wextra-semi)

src/oatpp/core/async/worker/IOEventWorker_epoll.cpp, src/oatpp/core/base/Environment.cpp, src/oatpp/network/tcp/client/ConnectionProvider.cpp, src/oatpp/network/tcp/server/ConnectionProvider.cpp
https://github.com/oatpp/oatpp/issues/784
=> Fix compiler warnings (-Wredundant-tags)

src/oatpp/core/async/Processor.hpp, src/oatpp/network/monitor/ConnectionInactivityChecker.hpp, src/oatpp/network/monitor/ConnectionMaxAgeChecker.hpp, test/oatpp/core/data/buffer/ProcessorTest.cpp, test/oatpp/network/monitor/ConnectionMonitorTest.cpp, test/oatpp/web/app/ControllerAsync.hpp, test/oatpp/web/app/ControllerWithInterceptorsAsync.hpp, test/oatpp/web/server/ServerStopTest.cpp, test/oatpp/web/server/handler/AuthorizationHandlerTest.cpp
See https://github.com/oatpp/oatpp/issues/784
=> Fix compiler warnings (-Wsuggest-override)

src/oatpp/core/concurrency/Thread.cpp
See https://github.com/oatpp/oatpp/issues/784
=> Fix compiler warnings (-Wmissing-declarations)

src/oatpp/network/tcp/Connection.cpp
See https://github.com/oatpp/oatpp/issues/784
=> Fix compiler warnings (-Wduplicated-branches)

src/oatpp/web/server/AsyncHttpConnectionHandler.cpp, src/oatpp/web/server/AsyncHttpConnectionHandler.hpp
There are no major changes, just to unify asynchronous APIs with regular APIs
=> Just a small fix

src/oatpp/core/async/Coroutine.cpp, src/oatpp/core/data/buffer/Processor.cpp, src/oatpp/network/Server.cpp, src/oatpp/network/tcp/Connection.cpp, src/oatpp/parser/json/Utils.cpp, src/oatpp/web/mime/multipart/StatefulParser.cpp
=> Fix compiler warnings (-Wswitch-default)

src/oatpp/core/async/Processor.cpp, src/oatpp/network/tcp/client/ConnectionProvider.cpp, src/oatpp/network/tcp/server/ConnectionProvider.cpp, src/oatpp/parser/json/mapping/Deserializer.cpp, src/oatpp/parser/json/mapping/Serializer.cpp, src/oatpp/web/client/ApiClient.hpp, src/oatpp/web/server/HttpProcessor.cpp
=> Fix compiler warnings (-Wswitch-enum)

test/oatpp/core/data/mapping/type/ObjectTest.cpp
=> Fix compiler warnings (-Wcatch-value=)

src/oatpp/core/provider/Pool.hpp
=> Fix compiler warnings (-Winfinite-recursion)

cmake/compiler-flags.cmake, test/oatpp/core/data/share/MemoryLabelTest.cpp, test/oatpp/web/PipelineAsyncTest.cpp, test/oatpp/web/PipelineTest.cpp
=> Fix compiler warnings (-Wunused-variable)

cmake/compiler-flags.cmake, src/oatpp/web/server/HttpProcessor.hpp
=> Fix compiler warnings (-Wctor-dtor-privacy)

src/oatpp/core/parser/Caret.cpp, src/oatpp/network/tcp/server/ConnectionProvider.cpp
See #784
Since #810 has some discussions, I pulled these from there.
=> Fix 2 trivial clang warnings

cmake/compiler-flags.cmake, src/oatpp/core/IODefinitions.hpp, src/oatpp/core/base/Environment.cpp, src/oatpp/network/tcp/server/ConnectionProvider.cpp, test/oatpp/core/data/stream/BufferStreamTest.cpp
=> Fix compiler warnings (-Wuseless-cast)

cmake/compiler-flags.cmake, src/oatpp-test/Checker.cpp, src/oatpp-test/UnitTest.cpp, src/oatpp-test/web/ClientServerTestRunner.hpp, src/oatpp/core/async/worker/IOEventWorker_epoll.cpp, src/oatpp/core/base/Compiler.hpp, src/oatpp/core/base/Environment.hpp, src/oatpp/web/mime/multipart/PartReader.cpp, src/oatpp/web/protocol/http/outgoing/MultipartBody.cpp, test/oatpp/AllTestsMain.cpp, test/oatpp/core/async/LockTest.cpp, test/oatpp/core/data/mapping/type/PrimitiveTest.cpp, test/oatpp/core/provider/PoolTest.cpp, test/oatpp/encoding/UrlTest.cpp, test/oatpp/network/ConnectionPoolTest.cpp, test/oatpp/network/monitor/ConnectionMonitorTest.cpp, test/oatpp/network/virtual_/PipeTest.cpp, test/oatpp/web/ClientRetryTest.cpp, test/oatpp/web/FullAsyncClientTest.cpp, test/oatpp/web/FullAsyncTest.cpp, test/oatpp/web/FullTest.cpp, test/oatpp/web/PipelineTest.cpp, test/oatpp/web/app/Controller.hpp, test/oatpp/web/app/ControllerAsync.hpp, test/oatpp/web/server/ServerStopTest.cpp
=> Fix compiler warnings (-Wsuggest-attribute=format)

cmake/compiler-flags.cmake, src/oatpp/core/parser/Caret.cpp, src/oatpp/encoding/Base64.cpp, src/oatpp/encoding/Hex.cpp, src/oatpp/encoding/Unicode.cpp, src/oatpp/network/Url.cpp
=> Fix compiler warnings (-Wconversion)

cmake/compiler-flags.cmake, src/oatpp/core/data/mapping/type/Enum.hpp
See #784 
This one is new compared to #810
=> Fix compiler warnings (-Wdangling-reference)

cmake/compiler-flags.cmake
=> Enable compiler warnings (-Wsuggest-attribute=cold)

cmake/compiler-flags.cmake, src/oatpp/network/tcp/Connection.cpp
=> Fix compiler warnings (-Wlogical-op)

src/oatpp/web/protocol/http/incoming/SimpleBodyDecoder.cpp
=> Fix issue with "100 Continue" response not sent correctly

cmake/compiler-flags.cmake, src/oatpp/core/data/buffer/Processor.cpp, src/oatpp/core/data/share/MemoryLabel.hpp, src/oatpp/core/data/share/StringTemplate.cpp, src/oatpp/core/utils/ConversionUtils.cpp, src/oatpp/web/protocol/http/incoming/SimpleBodyDecoder.cpp, test/oatpp/core/data/resource/InMemoryDataTest.cpp, test/oatpp/core/data/share/LazyStringMapTest.cpp, test/oatpp/core/data/stream/BufferStreamTest.cpp, test/oatpp/network/virtual_/InterfaceTest.cpp, test/oatpp/web/mime/multipart/StatefulParserTest.cpp, test/oatpp/web/protocol/http/encoding/ChunkedTest.cpp
=> Fix compiler warnings (-Wsign-compare)

src/oatpp/core/data/mapping/type/Collection.hpp, src/oatpp/core/data/mapping/type/Map.hpp, src/oatpp/core/data/mapping/type/Type.hpp, src/oatpp/core/data/share/MemoryLabel.hpp, src/oatpp/core/data/stream/Stream.hpp, src/oatpp/core/provider/Pool.hpp, src/oatpp/core/utils/ConversionUtils.hpp, src/oatpp/web/protocol/http/Http.hpp, test/oatpp/web/app/Controller.hpp, test/oatpp/web/app/ControllerAsync.hpp
=> Fix compiler warnings in headers (-Wsign-conversion)

src/oatpp/network/Url.cpp, test/oatpp/network/UrlTest.cpp
=> Fix url parse bug

src/oatpp/web/client/RequestExecutor.cpp
=> Fix client retry bug

src/oatpp/codegen/api_controller/base_define.hpp
=> Fix default value with QUERY macro

src/oatpp/parser/json/mapping/Deserializer.cpp, src/oatpp/parser/json/mapping/Serializer.cpp, test/oatpp/parser/json/mapping/DTOMapperTest.cpp, test/oatpp/parser/json/mapping/DeserializerTest.cpp
=> Fix serialize object and deserialize json when not include required field

cmake/compiler-flags.cmake
A minor patch per [issue 872](https://github.com/oatpp/oatpp/issues/872)
=> comment out fcf-protection

src/oatpp/core/data/mapping/ObjectMapper.hpp, test/oatpp/web/FullTest.cpp, test/oatpp/web/app/Client.hpp, test/oatpp/web/app/Controller.hpp
=> Fix the bug of send "null" in request body causes seg-fault

README.md, changelog/1.4.0.md, src/CMakeLists.txt, src/oatpp/codegen/dto/base_define.hpp, src/oatpp/codegen/dto/enum_define.hpp, src/oatpp/data/mapping/ObjectRemapper.cpp, src/oatpp/data/mapping/ObjectRemapper.hpp, src/oatpp/data/mapping/ObjectToTreeMapper.cpp, src/oatpp/data/mapping/ObjectToTreeMapper.hpp, src/oatpp/data/mapping/Tree.cpp, src/oatpp/data/mapping/Tree.hpp, src/oatpp/data/mapping/TreeToObjectMapper.cpp, src/oatpp/data/mapping/TreeToObjectMapper.hpp, src/oatpp/data/type/Enum.hpp, src/oatpp/data/type/Object.cpp, src/oatpp/data/type/Object.hpp, src/oatpp/data/type/Tree.cpp, src/oatpp/data/type/Tree.hpp, src/oatpp/json/ObjectMapper.cpp, src/oatpp/web/client/ApiClient.hpp, src/oatpp/web/server/api/ApiController.hpp, test/CMakeLists.txt, test/oatpp/AllTestsMain.cpp, test/oatpp/data/mapping/ObjectRemapperTest.cpp, test/oatpp/data/mapping/ObjectRemapperTest.hpp, test/oatpp/data/mapping/ObjectToTreeMapperTest.cpp, test/oatpp/data/mapping/TreeTest.cpp, test/oatpp/data/mapping/TreeToObjectMapperTest.cpp, test/oatpp/data/type/EnumTest.cpp
=> Object remapper

src/oatpp/async/Executor.cpp, src/oatpp/async/Executor.hpp
=> Fix std::thread assertion on destruction

src/oatpp/json/Utils.cpp, src/oatpp/json/Utils.hpp
=> Fix json serializer buffer overflow
